[build-system]
build-backend = "scikit_build_core.build"
requires = [
  "scikit-build-core>=0.10",
  "pybind11[global]>=2.10",
  "pybind11-stubgen>=0.10",
]

[project]
authors = [{ name = "Hanamy", email = "rongerch@outlook.com" }]
dependencies = ["numpy>=2.3,<2.4", "matplotlib", "casadi"]
description = "Reinforcement Learning for Tailsitter UAVs"
license = { text = "MIT" }
name = "minco-python"
readme = "README.md"
requires-python = ">=3.12"
version = "0.1.0"

[project.scripts]
demo = "examples.demo:main"

[tool.scikit-build]
cmake.args = []
wheel.packages = ["minco", "examples"]

[dependency-groups]
dev = [
  "ruff",
  "pre-commit",
  "pytest>=7.0",
  "pytest-cov",
  "pybind11-stubgen>=2.0",
  "pyyaml",
]

[tool.pytest.ini_options]
filterwarnings = [
  "ignore:The use of `x.T` on tensors of dimension other than 2:UserWarning",
]
python_classes = "Test*"
python_files = "test_*.py"
python_functions = "test_*"
testpaths = ["tests"]
