/global_planning_node:
  ros__parameters:
    BasicTrajectoryCirled: true
    BasicTrajectoryCurvatureFactor: 0.8
    BasicTrajectoryHeight: 6.5
    BasicTrajectoryRadius: 25.0
    BasicTrajectoryRate: 0.5
    BasicTrajectoryType: 2
    BasicTrajectoryWaveLen: 50.0
    BoxBackLength: 0.5
    BoxDownLength: 0.2
    BoxFrontLength: 0.5
    BoxSideInsideLength: 0.1
    BoxSideOutsideLength: 0.1
    BoxUpLength: 0.2
    Frame: world
    IntegralIntervs: 30
    PieceN: 10
    RelCostTol: 1.0e-05
    SmoothingEps: 0.01
    TrajectoryCirled: false
    UavScale: 1.0
    acc_max: 12.0
    acc_weight: 0.0
    omg_consistent_weight: 0.0
    omg_x_max: 0.8
    omg_x_weight: 20000.0
    omg_y_max: 2.5
    omg_y_weight: 10000.0
    omg_z_max: 0.8
    omg_z_weight: 20000.0
    thrust_max: 4.5
    thrust_min: -4.5
    thrust_weight: 10000.0
    time_weight: 10000.0
    trajTopic: /control_traj
    traj_pub_rsl: 0.02
    v_max: 12.0
    vel_weight: 10000.0
